### ISSUE TITLE
Collateral Working Group Minutes - March 28th 10 AM EST

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2055]
# CDM  Collateral Working Group Minutes

## Date
March 28th, 2023 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes (N/A)
- [x] Meeting Material [ISDA Common Domain Model - Collateral WG 28th March 2023.pdf](https://github.com/finos/common-domain-model/files/11065073/ISDA.Common.Domain.Model.-.Collateral.WG.28th.March.2023.pdf)
- [x] Introduction to the structure of the working group meetings 
- [x] CDM Collateral Working Group Objectives - Terms of Reference [ISDA CDM Collateral WG Terms of Reference- Version 7.pdf](https://github.com/finos/common-domain-model/files/11078095/ISDA.CDM.Collateral.WG.Terms.of.Reference-.Version.7.pdf)
- [x] Eligible Collateral Updates
    - Eligible Collateral – Change of data type name/label
    - Helper functions to simplify Eligible Collateral detail input
    - Next Steps re open-source access to CDM object builder
- [x] Cash Collateral Interest Contribution Update 
- [x] CDM 2023 Implementation updates
    - Acadia
    - Murex 
- [x] Structured Products WG
Host Rotation: Jean-Baptiste Ziade
Date: 4/11/23 (Monthly, second Tuesday, 10AM EST)
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1 - Requirement to update ‘Terms of Reference Document’ (TOR). The current version 7 of the TOR document is now due for a quarterly review and update. The current TOR refers to processes and rules defined by ISDA, before the project was moved to FINOS.
- [ ] Decision 2 - As referenced in agenda item 3, point 1 to contribute the Eligible Collateral change of data type name/label. Change from ‘Eligible Collateral Schedule’ to ‘Eligible Collateral Specification’ and updates to the related description. 

## Action Items
- [ ] Action 1 -  TOR Review and update, ISDA will work with FINOS, ISLA and ICMA to draft a new working groups TOR, some of the content will remain, additional scope and content to be added 
- [ ] Action 2 - Process contribution to CDM pull request No 2063 EligibleCollateralNameChange  https://github.com/finos/common-domain-model/pull/2063
- [ ] Action 3 - As refences in agenda item No 3 point 2. ‘Helper functions to simplify Eligible Collateral detail input’ ISDA will continue to work with members examples to validate the helper function and object builder further to construct complex multiple instances of data and the. Further examples welcome if other members have interest.
- [ ] Action 3 - As refences in agenda item No 3 point 2. ‘Helper functions to simplify Eligible Collateral detail input’ ISDA will continue to work with members examples to validate the helper function and object builder further to construct complex multiple instances of data and the. Further examples welcome if other members have interest.
- [ ] Action 4 - ISDA will give the working group an update related to the open sourcing of the CDM Object Builder UI tool at the next meeting schedules for 25th April 
- [ ] Action 5 - As referenced in agenda item No 4 - Cash Collateral Interest/Distribution Contribution. This work related to the parameters needed to calculate and process cash collateral interest initially developed for the ISDA CSA is pending contribution to the CDM. This structure has wider cases across other forms of collateral documentation including Custody and Prime Brokerage. Therefore extra time is needed for analysis to ensure compatibility going forward and reusability of existing data components related to interest rate products. ISDA will co-ordinate these next steps and update the working group in due course.

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09](https://www.google.com/url?q=https://zoom.us/j/96084284579?pwd%3DQTJ3bTBrMURkWXA1S0owa1djaEVIUT09&sa=D&source=calendar&ust=1679321977213933&usg=AOvVaw23MF-NXSYhgH1a0kW97eRo)

Meeting ID: 960 8428 4579
Passcode: 477790
Find your local number: [https://zoom.us/u/aoBkYnW9l](https://www.google.com/url?q=https://zoom.us/u/aoBkYnW9l&sa=D&source=calendar&ust=1679321977213933&usg=AOvVaw10_qYEyh7NMZlPH63lHEUB)

**Comment by valdensmith** [comment]
Testing

**Comment by Alexis25091972** [comment]
Received

Alexis Lucas
Vice President
Collateral Management Product – Clearance and Collateral Management (CCM)
The Bank of New York Mellon SA/NV
Boulevard Anspachlaan 1 | B-1000 Brussels
T +32.2. 545.8578 | M +32 479 70 92 12 | M +32 472 11 48 25 (Do not send text messages to M numbers)
***@***.******@***.***>
www.bnymellon.com<http://www.bnymellon.com/>

Your personal information will be collected and held by BNY Mellon Corporation and will be used for the purpose(s) of maintaining our business relationship. This includes but is not limited to providing you with reporting were appropriate as well as generic business and Markets updates, invitations etc. Your personal information could be shared within the BNY Mellon Group. Your personal information will never be shared with external third parties. BNY Mellon Corporation will transfer or store your personal information in other countries, including those outside Europe, under the protection of appropriate safeguards. For more information about how we collect, use and share personal information and your legal rights, see BNY Mellon’s full privacy notice https://www.bnymellon.com/emea/en/privacy.jsp.

**Comment by turntablistic** [comment]
received

Richard Barton
***@***.***
93 Longwater Circle, Norwell, MA 02061<webextlink://93%20Longwater%20Circle,%20Norwell,%20MA%2002061>
office +1 617-865-6834 | cell +1 609 509 8014
 www.acadia.inc<https://acadia.inc/>
***@***.******@***.******@***.***<https://www.linkedin.com/company/acadiasoft-inc>


From: valdensmith ***@***.***>
Date: Wednesday, March 22, 2023 at 6:46 AM
To: finos/common-domain-model ***@***.***>
Cc: Richard Barton ***@***.***>, Manual ***@***.***>
Subject: Re: [finos/common-domain-model] Collateral Working Group Minutes - March 28th 10 AM EST (Issue #2055)
CAUTION: External email warning. This email originated from outside acadia.inc. Beware of phishing attempts. Comply with all acadia.inc policy to confirm sender identity before responding, forwarding, and especially clicking links or opening attachments.


Testing

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffinos%2Fcommon-domain-model%2Fissues%2F2055%23issuecomment-1479319943&data=05%7C01%7Crichard.barton%40acadia.inc%7Ca943b008c8314ccbdfb708db2ac2ac6b%7Cf432debe2aae495fb2dfe8458cace1da%7C0%7C0%7C638150787836785137%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DGT8%2FidOH5d6BXXbMolQobepmU1KOQ7iinxQZQ%2BdTlY%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA6T2VRK3TW2TXDDTKYR3QK3W5LJ7ZANCNFSM6AAAAAAV5Q3ECY&data=05%7C01%7Crichard.barton%40acadia.inc%7Ca943b008c8314ccbdfb708db2ac2ac6b%7Cf432debe2aae495fb2dfe8458cace1da%7C0%7C0%7C638150787836785137%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wjFS9Eb7YT2cAWlu4gYLwkPPtCtAcPkyuKtcEzCHe0s%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

The information contained in this e-mail, and any attachment, is confidential and is intended solely for the use of the intended recipient. Access, copying or re-use of the e-mail or any attachment, or any information contained therein, by any other person is not authorized. If you are not the intended recipient please return the e-mail to the sender and delete it from your computer. The acadia.inc privacy policy is available on our website.

**Comment by valdensmith** [comment]
Vernon Alden-Smith

**Comment by RonAtCFX** [comment]
ron Kaim / CFX

**Comment by mcleo-d** [comment]
James McLeod / FINOS

**Comment by jgavronsky** [comment]
Jane Gavronsky / FINOS

**Comment by turntablistic** [comment]
Richard Barton/Acadia

**Comment by adamulman** [comment]
Adam Ulman/SmartStream

**Comment by ronaldssebalamu** [comment]
Ronald Ssebalamu / FINOS

**Comment by SergioGuirreri** [comment]
Sergio Guirreri / Reply

**Comment by iansloyan** [comment]
Ian Sloyan / ISDA

**Comment by eteridvalishvili** [comment]
Eteri Dvalishvili / FINOS

**Comment by CarltonOrola** [comment]
Carlton Orola / EquiLend (first 30 min)

**Comment by syoon078** [comment]
Sarah Yoon / FORVIS

**Comment by CrisSearle** [comment]
Cris Searle / Clearstream

**Comment by Alexis25091972** [comment]
Alexis Lucas
Vice President
Collateral Management Product – Clearance and Collateral Management (CCM)
The Bank of New York Mellon SA/NV
Boulevard Anspachlaan 1 | B-1000 Brussels
T +32.2. 545.8578 | M +32 479 70 92 12 | M +32 472 11 48 25 (Do not send text messages to M numbers)
***@***.******@***.***>
www.bnymellon.com<http://www.bnymellon.com/>

Your personal information will be collected and held by BNY Mellon Corporation and will be used for the purpose(s) of maintaining our business relationship. This includes but is not limited to providing you with reporting were appropriate as well as generic business and Markets updates, invitations etc. Your personal information could be shared within the BNY Mellon Group. Your personal information will never be shared with external third parties. BNY Mellon Corporation will transfer or store your personal information in other countries, including those outside Europe, under the protection of appropriate safeguards. For more information about how we collect, use and share personal information and your legal rights, see BNY Mellon’s full privacy notice https://www.bnymellon.com/emea/en/privacy.jsp.

**Comment by paulpkelly** [comment]
Paul Kelly / Logical Construct

**Comment by BenAJohnson** [comment]
Ben Johnson - FORVIS

**Comment by lolabeis** [comment]
Leo Labeis - REGnosys

**Comment by AmyCaruso** [comment]
Amy Caruso - ISDA

**Comment by eacunaISDA** [comment]
Eleonora Acuña - ISDA

**Comment by AdamRGoddard** [comment]
Adam Goddard - Forvis UK

**Comment by turntablistic** [comment]
Apologies had to drop for another call
