### ISSUE TITLE
Change tradeDate from date type to zonedDateTime

### ISSUE THREAD

**Issue by tomhealey-icma** [finos/common-domain-model#2205]
The Trade type does not include the ability to define the trade date with a time and timezone. A Product type could be created with relative dates. Example: An overnight repo can be defined in terms of a relative start date and the next business day. The actual start date will depend on the agreement between the counterparties, venue, or other third parties when the trade is executed and where it is executed.

Workflow and business event dates refer to other types of events. Workflows are actions that take place throughout the execution and lifecycle process but remain separate from the trade date which is agreed to by the counterparties. The same is true with a business event. An execution event may take place at one date and time while the trade date agreed to by the counterparties may be different.

The proposed solution is to change the Trade->tradeDate to zonedDateTime with reference to a business center or add a separate Trade->tradeDateTime with type zonedDateTime and deprecate tradeDate in the future.

**Comment by chrisisla** [comment]
I agree that a trade time and timezone would be beneficial on the trade, but I think this should be separate to the trade date. I have not heard of counterparties agreeing a trade time, but this is not to say this is always the case. My suggestion would thus be to not change the usage or structure of tradeDate but add new items for the trade time/timezone as required.

**Comment by lolabeis** [comment]
I agree with the comments above re separating the trade date and time (and having that second one optional only).

But I would also point-out that the direction of travel for the CDM generally was to _do away_ with trade date as an attribute of the trade itself. The reason is that if trade date is about:
1) recording when the trade event took place, it belongs to the event date on the execution event
2) a date that matters for the contract mechanics (e.g. calculating accruals or settlement), it belongs to the product's effective date

Therefore, further entrenching trade date at trade level by adding time / location would work against that objective.

If it's about needing time or location for case 2), could you include some term sheet language that explicitly references those?

**Comment by tomhealey-icma** [comment]
I have separated the tradeDate and tradeTime. Please see, [PR2210](https://github.com/finos/common-domain-model/pull/2210). 

I'll give you a couple scenarios why this is necessary:

One scenario is where a repo security (security + term) is defined as a spot-next has a start-date equal to the trade-date plus 2 days and a end date equal to the next business day after the spot date. These dates are not known until the trade is agreed to, so the effective date is relative to the trade date and the end date is relative the start-date. You could assume the trade date and event date are the same but this is not always the case either, which leads to second scenario.

The trade date is a contractual agreement attribute between the counterparties which is different than the date when the event took place. Two counterparties agree today (event date) to document a transaction that is back-dated to yesterday (trade date). The start date for accrual purposes is tomorrow, thus a separate effective date. 

Because the business event is outside the contractual agreement (trade + product) and the business event changes with each lifecycle or modification event it is not a reliable event date for contractual purposes.

**Comment by tomhealey-icma** [comment]
PR submitted and approved.

**Comment by lolabeis** [comment]
Reopening and linking to PR instead. Will get closed once PR is merged.
