### ISSUE TITLE
NaturalPerson and NaturalPersonRole model contains circular reference

### ISSUE THREAD

**Issue by hugohills-regnosys** [finos/common-domain-model#2257]
The model type `NaturalPerson` contains a list of `NaturalPersonRole`, and `NaturalPersonRole` has a reference back to the containing type `NaturalPerson` causing a circular reference in the model.

```
type NaturalPerson: 
	[metadata key]
	personId PersonIdentifier (0..*) 
		[metadata scheme]
	honorific string (0..1) 
	firstName string (0..1) 
	middleName string (0..*) 
	initial string (0..*) 
	surname string (0..1) 
	suffix string (0..1) 
	dateOfBirth date (0..1) 
	contactInformation ContactInformation (0..1) 
	personRole NaturalPersonRole (0..*) // change to NaturalPersonRoleEnum?
```

```
type NaturalPersonRole: 
	personReference NaturalPerson (1..1) 
		[metadata reference]
	role NaturalPersonRoleEnum (0..*) 
		[metadata scheme]
```

```
type Party: 
	[metadata key]
	partyId PartyIdentifier (1..*) 
	name string (0..1) 
		[metadata scheme]
	businessUnit BusinessUnit (0..*) 
	person NaturalPerson (0..*) 
	personRole NaturalPersonRole (0..*) // remove?
	account Account (0..1) 
	contactInformation ContactInformation (0..1) 
```

**Comment by hugohills-regnosys** [comment]
The type of attribute `NaturalPerson-> personRole` should be changed to `NaturalPersonRoleEnum`.

However, there would then be 2 different ways to specify a `NaturalPerson` role on a `Party`:
1. Specify `Party->person` and `Party->personRole` (where `Party->person->personRole` is blank)
2. Specify `Party->person` and `Party->person->personRole` (where `Party->personRole` is blank)

**Comment by iansloyan** [comment]
Party does not have partyrole in it either and has party inside as partyReference in similar manner.
Question is should be role reference the party or party reference the role. I think it could be the former on reflection. Party Role tends to be used more in event model to say who are the actors on a function/event rather than as a universal declaration of a party's role on a trade. The only exception to that is Party 1 and Party 2 which is dealt with differently using counterpartyRole.

**Comment by lolabeis** [comment]
`NaturalPerson` and `NaturalPersonRole` should mirror `Party` and `PartyRole`. This means the `personRole` attribute should be removed from `NaturalPerson`, rather than being replaced by an enum.

The reason why `Party` can contain both `naturalPerson` and `naturalPersonRole` is because the former defines the person(s) while the latter just defines their roles, with the `naturalPerson` attribute in `naturalPersonRole` being a reference (so it's not defined 2x). This is similar to `Trade` having both `party` and `partyRole` attributes, with `party` being a reference in the latter.

**Comment by ebataller** [comment]
The proposed solution to close this issue is in this [PR](https://github.com/finos/common-domain-model/pull/2545).

**Comment by ebataller** [comment]
The proposed solution for prod version is included in this [PR](https://github.com/finos/common-domain-model/pull/2576).
