### ISSUE TITLE
Proposed lapse of Maintainer: Ian Sloyan (@iansloyan)

### ISSUE THREAD

**Issue by chrisisla** [finos/common-domain-model#2770]
As raised at the last SWG (Issue https://github.com/finos/common-domain-model/issues/2739) it has been proposed that the maintainer status of @iansloyan is to lapse. This frees up space for new maintainers, and also follows on from a similar situation with Nigel Cobb, whose new role also meant that like Ian he could no longer commit the time needed to actively maintain the CDM.

Could the current maintainers please indicate their approval by comment/thumbs up reaction below please. Proposal that majority approval will then be actioned at the next SWG in April.

**Comment by chrisisla** [comment]
+ @llynhiavu

 (as can only assign 10 people to an issue and we have >10 maintainers currently)

**Comment by dshoneisda** [comment]
No objection assuming Ian is aware and consents

**Comment by chrisisla** [comment]
> No objection assuming Ian has also been made aware

Yes, I have spoken to Ian separately about this and sent him a link to this Issue.

**Comment by jgavronsky** [comment]
@chrisisla -- Your proposed removal of @iansloyan as maintainer states that Ian can "no longer commit the time needed to actively maintain the CDM". 
It is my observation that Ian is currently contributing a significant amount of work to the CDM on a weekly basis, so this does not seem to align for me. 

Broadly speaking, as individual maintainers move organizations, it is an indication of a healthy project and community if they are able to continue with their level of contribution (which may occur on an individual, non-affiliated basis or as part of their new employment). Certainly with Ian's current level of contribution to the standard there seems to me no reason for action on the maintainer list. 

Regarding the more than 10 maintainers - I don't see a problem with having many maintainers; in fact, this will help with covering the work. Assigning 10+ maintainers to an issue does not seem like a productive option (comment from @chrisisla seems to indicate a need to do so); rather, I would think that certain maintainers will specialize in specific areas of the standard and issues would be allocated for resolution accordingly.

I warmly recommend establishing a regular maintainer meeting to assess the current outstanding work and "hand out" tasks for resolution of issues and approval of PR's (tagging specific maintainers), and including Ian in the process. Creating and maintaining a broad diversity of organizations and maintainers is a sign of growing project health, so I would encourage that the maintainer cohort continue to welcome more maintainers into their midst.

**Comment by mindthegab** [comment]
Hey @chrisisla 

> (as can only assign 10 people to an issue and we have >10 maintainers currently)

issues + assignees might not be the best way to run a vote with 10+ voters. You might want to consider:

1. A [github discussion poll](https://github.blog/changelog/2022-04-12-discussions-polls/) - making it clear that the only binding votes are from maintainers.
2. A good old email list +1 / -1 vote (see [fdc3](https://groups.google.com/a/finos.org/g/fdc3-participants/c/MTjbRaA-C14/m/rqAN8INiAgAJ) as an example)
3. Tagging folks as you did for the 11th maintainer, rather than assigning the voting issue to them

Hope this helps!

**Comment by chrisisla** [comment]
Hi @mindthegab 
Yes, agreed, on this occasion I assigned the issue as I wanted to make sure that the current maintainers were notified as I felt the election of maintainers was more important then just a mention. At the time I didn't know of the 10 assignee limit on an Issue so going forward I'll use one of the options you have suggested above.
Thanks!

**Comment by chrisisla** [comment]
Hi @jgavronsky ,

I appreciate your perspective may differ, but from looking at the Issues, Meeting Notes and Pull Requests on the CDM github repository it does not appear that Ian has been very involved with the initiative for an extended period of time. 

My understanding is that Ian is currently contracted to FINOS. In the past the participation of FINOS employees in relation to maintainership has been discussed, and my recollection is that you confirmed that FINOS employees would not be maintainers in any FINOS projects, as this could be construed as a conflict of interest i.e. FINOS facilitate the project but should not have a vote on the direction of a project, which is one of the roles of a maintainer.

I’m not sure where your point about allocating work to maintainers has come from as this is not mentioned on this Issue?

I agree with your final point about welcoming more maintainers to the project, as we do need more people and firms to become actively engaged with the modelling, governance, administration and working groups in general.

**Comment by chrisisla** [comment]
Having spoken to a number of the maintainers the general feeling is that elections like this are best performed over email or other mediums rather than using github Issues. I will email all the maintainers to organise the vote and update this Issue with the results once confirmed.

**Comment by iansloyan** [comment]
Hi All

As discussed I am happy to persist as a maintainer - but the governance process means that maintainers from a trade association are required to approve PRs. Thus there is not too much for me to do unless invited to comment or review an issue or PR. So take it as given I am open to comment and review things if I can help! I think at the very least the core design principles of the CDM are something that I can advise on if consulted into a PR or Issue.

As regards to this change, the reason of freeing up space was noted, I was not aware of a limit of 10 maintainers (excluding the GitHub issue assignment limitation), where is that written as a requirement for the project? If that is written in the docs, that might be something worth considering revising as there may be expertise that is being limited across a model that covers a wide array of financial market products and many use cases and technical fields. I was of the impression that the role of maintainer should be as the guardians of the standard from technical level all the way to the strategic level rather than in the narrow sense GitHub role that allows approval of a GitHub PR.

Happy to join a discussion on this with other maintainers as I am keen to understand the reasoning for urgent action also.

**Comment by chrisisla** [comment]
Hi @iansloyan ,

Can you point me to where in the documentation it says that PRs have to be approved by members of a trade association please? I do not believe this to be the case, and as I am sure you are aware, REGnosys are regularly reviewing and approving PRs as active maintainers of the CDM. 

There is currently no restriction on the number of maintainers - as you will see from the Issues list we are hoping to invite two more imminently. 

We're actively looking at the governance now, and have been for the last few months, and there are a number of Discussions open at the moment about how we can ensure that this is more open. If you have any suggestions then please add some comments on them and let us know.

**Comment by iansloyan** [comment]
> Hi @iansloyan ,
> 
> Can you point me to where in the documentation it says that PRs have to be approved by members of a trade association please? I do not believe this to be the case, and as I am sure you are aware, REGnosys are regularly reviewing and approving PRs as active maintainers of the CDM.
> 
> There is currently no restriction on the number of maintainers - as you will see from the Issues list we are hoping to invite two more imminently.
> 
> We're actively looking at the governance now, and have been for the last few months, and there are a number of Discussions open at the moment about how we can ensure that this is more open. If you have any suggestions then please add some comments on them and let us know.

The README refers to the following slides (link below) - and slide 2 details in a matrix the requirements for PRs to be approved by (1 or 2) TA staff unless it is a bug fix or technical change which can be approved by any maintainer (such as REGnosys or TradeHeader pushing through tech changes as different work progresses.

https://github.com/finos/common-domain-model/files/11372524/FINOS.Maintainers.Issue.and.Pull.Request.Approval.Process.pptx

Happy to contribute to the governance discussion - I will contact you to discuss.

**Comment by chrisisla** [comment]
This motion has been successfully carried by unanimous vote of the CDM Maintainers. The decision will be ratified at the next CDM Steering Working Group on April 16th.
