### ISSUE TITLE
CDM Build are failing due to permissions

### ISSUE THREAD

**Issue by PayalKhanna** [finos/common-domain-model#2778]
All CDM build  are failing to deploy Daml/Scala/CSharp etc to oss.sonatype with `status: 401 Unauthorized`

https://g.codefresh.io/public/accounts/regnosysops/builds/65f1c20644013ff97cee2331

This is blocking releases.

**Comment by hugohills-regnosys** [comment]
All CDM builds fail due to an external authorisation issue that prevents the deployment of certain files types to Maven Central (which is where the CDM artifacts are publicly accessed from).

The deployment of `.zip` and `.tar.gz` artifacts fail with `status: 401 Unauthorized`, so affects DAML, C#, Scala, Typescript, Go, Python, Excel, JSON Schema artifacts.  The deployment of `jar` files is successful, so Java and Kotlin artifacts are unaffected.

All merging and releases will be blocked until this issue is resolved.
